const mangoose= require("mongoose")
const {ObjectId}=mangoose.Schema
const productSchema= new mangoose.Schema({
    name:{
        type:String,
        trim:true,
        required:true,
        maxlength:40
    },
    description:{
        type:String,
        trim:true,
        required:true,
        maxlength:2000
    },
    price:{
        type:String,
        trim:true,
        required:true,
        maxlength:32
    },
    category:{
        type:ObjectId,
        ref:"Category",
        required:true
    },
    stock:{
        type:Number,
    },
    sold:{
        type:Number,
        default:0
    },
    photo:{
        data:Buffer,
        contentType:String
    }
},{timestamps:true})
module.exports=mangoose.model("Product",productSchema);